site_name: SIAPES
site_description: Sistema de acompanhamento de pesquisa COPPE/UFRJ
theme: 'material'
theme_dir: 'docs/theme'
markdown_extensions:
  - plantuml
  - tables
  - graphviz
pages:
- Introdução: 'index.md'
- Visão: 'VISION.md'
- Medição: 'MEASUREMENT.md'
- Requisitos: 'REQUIREMENTS.md'
- Casos de Uso: 'models/USECASES.md'
- Plano de Testes: 'models/TESTPLAN.md'
- EAP: 'models/EAP.md'
- Diagrama de Classe: 'models/CLASSDIAGRAM.md'
- Relatórios: 'reports/README.md'
